services:
  db:
    image: postgres:16
    container_name: study-guide-postgres
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: study_guide
    ports:
      - "55432:5432"
    volumes:
      - study_guide_db:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: study-guide-redis
    ports:
      - "6380:6379"
    volumes:
      - study_guide_redis:/data

volumes:
  study_guide_db:
  study_guide_redis:
